### ISSUE TITLE
Please Review All Links Work

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#103]
While testing the Sweat and Toil application I noticed that a lot of the links got "Page not Found" or 404 errors because either the page was removed or changed when the ILAB moved to Drupal. So please verify that all the links work and don't redirect first. On the "About Comply Chain App" under the closed section "Why did the Department of Labor develop this App?" the link that a starts with "List of Goods Produced..." gets a page not found error message, along with the link "technical assistance projects".

**Comment by jfc3-dol** [comment]
The link issue has not been fixed since I'm still getting a page not found error message for the link mentioned above. I am getting the same page not found error message for the link "technical assistance projects" farther down the screen.

Please review all the links because some are not working.

Another question is, why are some links opening in the application and others in the Safari browser?

**Comment by pbhatt17** [comment]
All links are updated as per ILAB updates.
If the link is html type it'll open in the application whereas pdf link will open in the Safari browser.

**Comment by Abychalil** [comment]
All the links within the Comply chain App is retested and updated with the correct links. All links that were throwing 404 error is now fixed.

**Comment by KyleLivingstonDOL** [comment]
John, I checked the Reports Links and they are working

ZTI, can you please replace the Technical Assistance link with this: https://www.dol.gov/agencies/ilab/projects

**Comment by jfc3-dol** [comment]
@harpreetsdev @Abychalil @pbhatt17

Closing the issue because I assume these have been fixed or a new issue created if a link was broken still.
