### ISSUE TITLE
Web - Bookmark Screen - Keyboard User Can Not Tell if They are on the Remove Bookmark Icon

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#108]
I can now delete the bookmark with the keyboard, but a keyboard-only user can not tell where they are on the screen. There is no visual indication of where they are on the screen for either IE 11 or Chrome where they are on the screen since there is no visible focus. Also, need to check the visual focus for the keyboard user on the links too here and other places in the application.

Look to add **:focus** and **:active** to the CSS for the links and icons that are links too.

**Comment by KyleLivingstonDOL** [comment]
John, can you please let me know where the focus ring should default to once the delete bookmark is done? Also, I believe this is a continuation of a previous 508 issue. Can we make sure to link these issues together?

**Comment by jfc3-dol** [comment]
@KyleLivingstonDOL,

Once a bookmark is deleted, it should focus on the next item below it, which in some cases might be the next bookmarked item and others if it's the last one, then the first footer item.

The same process applies to the iOS and Android versions of the application.

Yes, you can link similar issues together to make sure both are completed before moving things to PROD.

**Comment by Abychalil** [comment]
Addressed this issue. Please retest and verify whether it meets the required 508 standards.
@jfc3-dol

**Comment by jfc3-dol** [comment]
@Abychalil,
It seems when the user deletes a bookmark from the list that the cursor focuses back to the first bookmark after giving them time to undo their delete. But if they "Undo" the delete, the focus moves to the "Bookmarks" button/link in the footer. I would expect the focus to go back to the item the person undeleted.

I'm going to leave this open while we see if that works/makes sense to others.

**Comment by jfc3-dol** [comment]
@Abychalil 
The same is still happening, as mentioned above, comment from February 25.

**Comment by jfc3-dol** [comment]
@Abychalil,
When the user deletes a bookmark from the list that the cursor focuses back to the first bookmark after giving them time to "Undo" their delete. 

It's still an issue if they use the "Undo" the delete button, where the focus moves to the "Bookmarks" button/link in the footer. I would expect the focus to go back to the item the person undeleted.

**Comment by jfc3-dol** [comment]
@Abychalil 

Okay, I will look at this issue and #80 related to bookmarks when you have had time to fix them.

**Comment by harpreetsdev** [comment]
@jfc3-dol 
The issue we are facing here is that once the bookmark gets deleted and "undeleted" using the undo button, it does get added back to the bookmark list on page in the correct sequence but there is a change in item (bookmark) id during that transition, so the piece of code that is supposed to return focus - "document.getElementById(restoredBookmark).focus()" returns a Null pointer error even though the undeleted bookmark logs correctly in the console while debugging the issue.
As an alternate solution we have restored the focus going to the First bookmark on the list after the undo bookmark button gets pressed and a bookmark is 'undeleted'.
Please let me know what you think.

**Comment by jfc3-dol** [comment]
@harpreetsdev 

That sound like it would be a better solution than being placed in the footer.

I will have to give this a look tomorrow since I got a lot of other items to review this week for something that is going live Monday. So I need to check on a few other things before the end of today.

**Comment by harpreetsdev** [comment]
@jfc3-dol  No problem at all, take your time.

**Comment by jfc3-dol** [comment]
@harpreetsdev 

I think, as you mentioned focusing on the first bookmark after a user uses the Undo button would be best.

After testing with JAWS in IE 11 and Chrome, I noticed IE 11 focused in the footer section, and Chrome focused back to the top of the page. Neither of those is that useful to the user.

What will happen if the user removes the first bookmark and then uses the Undo button to restore it? Will the focus go to the first bookmark still, or might it be better to focus on the "Bookmarks" heading? 

I think the best thing would be to focus on the first bookmark in the list if possible.

I am looking forward to the update to see how things work.

**Comment by harpreetsdev** [comment]
@jfc3-dol 

We've set it to focus on the first bookmark in case the bookmark delete gets undone by the user. 

In case the user deletes the first bookmark and pressed Undo button it'll stay on the first bookmark. It won't go to the Heading.

The code is structured to refresh the list and focus on the first bookmark.

**Comment by jfc3-dol** [comment]
@harpreetsdev 

Okay, that makes sense wanted to check what would happen if the first bookmark was removed and then undone.

Does the same apply if there is only one bookmark, and it's re-added using the Undo button?

Either way, looking forward to testing once the server/website is updated.

**Comment by harpreetsdev** [comment]
@jfc3-dol  

Yes for a single bookmark too, same logic applies.

**Comment by jfc3-dol** [comment]
@harpreetsdev @Abychalil @pbhatt17

Closing this issue about not being able to see the Remove Bookmark icon since people I can now see the focus ring/border in IE 11, Edge, Firefox, and Chrome now.

**NOTE**: Some of the information in this issue is related to the functioning of the Bookmark and Undo button ( #80 ) so will note that and then mentioned in that issue.
