### ISSUE TITLE
Android - General - Can Not Activate Steps Button in Menu with TalkBack

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#11]
When using TalkBack and a person opens the “Menu” they can’t activate the button that shows all the different Steps.

**Comment by KyleLivingstonDOL** [comment]
Hi John,

I think we've rectified this issue. When we resubmit for 508 compliance check, we can see if it is still doing this.

Thanks,
Kyle

**Comment by jfc3-dol** [comment]
Looking forward to testing the changes for the next build.

**Comment by KyleLivingstonDOL** [comment]
> Looking forward to testing the changes for the next build.

UAT for Sprint 7 (which is ongoing right now) will start on June 10.

**Comment by jfc3-dol** [comment]
I'm now able to activate the different Steps in the menu. But when I open the "Steps to a social compliance system' menu item, it then moves TalkBack's focus to the top of the application, and I have to read back through everything against to get to the Steps.

I am going to close this issue and open a new one for that issue.
