### ISSUE TITLE
Web - Main Screen - Visual Focus Moves on Screen but Keyboard Focus Stays at Menu Button

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#111]
When tabbing on the main Comply Chain screen, the visual focus moves on the screen, but the keyboard focus stays at the Menu button. So when a user sees the visual focus where they want and hits the "Enter" key, it opens the main "Menu" instead of what they wanted. Plus, there seem to be two tab stops for each menu item in the main content section of the page. Also, every time I tab JAWS reads "Menu button" when I'm not there.

**Comment by Abychalil** [comment]
Hi John, Can you please recheck this issue and see its still there? When I tested this issue in my system,  I couldn't found the mentioned bug. When I tab on elements on the index page, the keyboard is moving through all the items and I can open focused item when the I press the enter key. Attaching a screenshot showing that focus is on step:2. Please advise if tried to recreate it in the wrong way.
![1](https://user-images.githubusercontent.com/49654920/68138301-569c3b00-fef6-11e9-86e8-b65b4adb7229.PNG)

**Comment by jfc3-dol** [comment]
@KyleLivingstonDOL,

It might be easier to show you what I'm talking about because there is a difference between visual focus and keyboard focus because if the visual focus is one place and the user hits enter or tab, they are expecting one thing where the visual focus is, and it's not truly there.

**Comment by jfc3-dol** [comment]
@KyleLivingstonDOL,

Looking through old mail in the "Other" tab, I noticed this issue was there and still open.

I re-tested the ability to open links from the Menu in IE 11, Edge, Chrome, and Firefox and was able to open the links instead of opening and closing the Menu button.

So I'm going to close this issue.
