### ISSUE TITLE
Android - Gerneral - TalkBack Reading Sub-Navigation as Numbers Only

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#12]
TalkBack reads what looks like sub-navigation as a number. TalkBack should read it as “Step four”, “Step five”, etc. for example instead of four and five.

**Comment by KyleLivingstonDOL** [comment]
Hi John,

We've updated this and will be demo'ed on the next 508 compliance check after Sprint 7.

Best,
Kyle

**Comment by KyleLivingstonDOL** [comment]
It looks like this is done. UAT for Sprint 7 (which is ongoing right now) will start on June 10.

**Comment by jfc3-dol** [comment]
Thanks, for correcting that but TalkBack is reading "Step one one" instead of only Step one".

**Comment by KyleLivingstonDOL** [comment]
ZTI, please address.

**Comment by jfc3-dol** [comment]
The Steps in the sub-navigation are being read for example as "Step five", "step 6", etc. So I'm going to close the issue.
