### ISSUE TITLE
iOS - Voiceover Higlights are Not near What They are Reading

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#124]
For some reason now, when VoiceOver reads and item, the highlight is not around/near what is being read as it used too.

Please see the attached screenshots for different screens.

**English not highlighted on Spanish Menu.**

![comply chain - iso - menu - voice over not highlighting Anglais as expected when reading it so it shows above](https://user-images.githubusercontent.com/10423487/74770529-6ac43800-525a-11ea-96cd-fabae5e2918a.png)

**Bookmark "Undo" button.**

![comply chain - ios - bookmark screen - Voice Over is highlighting above the Undo button when it is reading it](https://user-images.githubusercontent.com/10423487/74770530-6ac43800-525a-11ea-8a4f-b8e6d0f9d00a.png)

**Bookmark in footer,**

![comply chain - ios - home screen - Voice Over is highlighting above the bookmarks button in the footer when it is reading it](https://user-images.githubusercontent.com/10423487/74770532-6ac43800-525a-11ea-96a6-fda3d6bb54ef.png)

**Comment by Abychalil** [comment]
@jfc3-dol 
We couldn't recreate this issue. Can you please retest and verify if this issue still existing?

**Comment by jfc3-dol** [comment]
@Abychalil 

Yes, it seems this issue has been corrected.

So I'm going to close it.
