### ISSUE TITLE
Android - General - TalkBack Reading Past End of Menu Items

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#14]
When the “Menu” is open Talkback will continue to read the content behind it instead of stopping as expected when it gets to the end of the list of menu items.

**Comment by KyleLivingstonDOL** [comment]
Hi John,

We've updated this and will be demo'ed on the next 508 compliance check after Sprint 7.

Best,
Kyle

**Comment by KyleLivingstonDOL** [comment]
It looks like this is done. UAT for Sprint 7 (which is ongoing right now) will start on June 10.

**Comment by jfc3-dol** [comment]
Closing issue since TalkBack stopped at the end of the Menu list of items as expected.
