### ISSUE TITLE
Web - About List Stays Open in Chrome when Clicking Last Link

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#148]
When the About list of links is open in Chrome and you click the last link it stays open, but closes as expected in IE 11, Edge, and Firefox along with any of the other links in the About list.

The issues is related to JIRA issue CCP   - 138.

**Comment by harpreetsdev** [comment]
@jfc3-dol 

This might be a cache related issue with chrome. It is working fine as expected when I test in chrome. Please clear your browser cache and try again.

@pbhatt17 @Abychalil

**Comment by jfc3-dol** [comment]
@harpreetsdev @pbhatt17 @Abychalil

I thought I did a hard refresh a few times in Chrome before I started any testing items I was reviewing. 

After doing it a few times this morning in Chrome, it looks like the issue is not there, so I'm going to close the issue.
