### ISSUE TITLE
Android - Home Screen - Why is Question Missing from Screen but in Menu

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#16]
Why is the question “What are Child Labor and Forced Labor?” in the “Menu” list but not on the home page? I would have thought the questions would be in both places or not in the "Menu". In the previous version, the question was in both places.

**Comment by KyleLivingstonDOL** [comment]
Hi John,

Thanks for this concern. We received direct user feedback to limit the amount of content on the homepage as much as possible. Can you please elaborate on the 508 compliance issue so we can better address it?

Best,
Kyle

**Comment by jfc3-dol** [comment]
It's not an accessibility issue but a functional question.

I wanted to make sure that the question was not mistakenly left off the home page since in previous version of the application it was on the home page and in the "Menu". 

If that is the way it's supposed to be, I'm going to close the issue.
