### ISSUE TITLE
VoiceOver, JAWS, and TalkBack is Not Reading Spanish and French with the Proper Accent

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#166]
While testing with VoiceOver, JAWS, and TalkBack and choosing Spanish or French the language displays the proper language text but reads all of them with an English accent. 

Please see the attached screenshot showing Spanish text with the page language still set to English.

**Spanish text with English language set.**

![ilab - comply chain - language not setting properly](https://user-images.githubusercontent.com/10423487/101059004-c9de0980-355b-11eb-94dc-09cbb77b53ff.png)

**Each language button has the correct language set for them.**

![ilab - comply chain - menu language buttons are setting properly](https://user-images.githubusercontent.com/10423487/101059007-ca76a000-355b-11eb-8a2a-38a005b67d83.png)

**Comment by jfc3-dol** [comment]
@harpreetsdev @pbhatt17 @Abychalil

On the web version I did a quick test were I changed the language from lang="en" to lang="es" for the Spanish text using INSPECT and JAWS read text with the proper language and accent. I could show you what I mean later.

**Comment by harpreetsdev** [comment]
@jfc3-dol  With regards to Today's release please find a couple notes on the 508 progress this sprint. 

1) Please test this issue along with #125. We implemented a fix that seems to be changing the page language.
2) Issues #66 and #67 need to be tested as well. Heading issues have been fixed.

  Also is there a priority you have in mind for the 508 issues? If you feel some bugs are causing bigger issues than others, please let us know and we can change priorities. Currently we are treating them as equal priority bugs.

@pbhatt17 @Abychalil.

**Comment by jfc3-dol** [comment]
@harpreetsdev @pbhatt17 @Abychalil.

When I was on a call with Sandi about color contrast, I showed her the language part on Teams with JAWS, and it wasn't working. Then I talked with @YerraSarath to ask him if the latest code was there.

I noticed that the language was changed in DEV tools, but if I refreshed the screen because there might have been an issue, it set the language back to English even though the text was not in English.

Do you have time to do a Teams call this week?

**Comment by harpreetsdev** [comment]
@jfc3-dol 
Sure, we can have a chat Thursday afternoon or Friday morning. Please let me know what time works for you.

@pbhatt17 @Abbychalil

**Comment by jfc3-dol** [comment]
@harpreetsdev @pbhatt17 @Abbychalil

I have time this afternoon (Thursday) from 1:30 PM - 5:30 PM. I could do Friday morning, but Thursday would work better.

**Comment by harpreetsdev** [comment]
@jfc3-dol 
Sure we can do today. Does 3.30 PM work for you?

@pbhatt17 @Abychalil

**Comment by jfc3-dol** [comment]
@harpreetsdev @pbhatt17 @Abbychalil

Sure 3:30 PM today works. I will send you a Teams invite and please forward to anyone else that should attend.

**Comment by harpreetsdev** [comment]
@jfc3-dol 
Sounds good.

**Comment by jfc3-dol** [comment]
@harpreetsdev @pbhatt17 @Abbychalil

I am leaving this issue one until we figure out issue #172 ( Web - Page Language Changes on Page Refresh but Text Stays in non-English Language ). I want to make sure if there is a fix, it works here too.

**Comment by jfc3-dol** [comment]
I am going to continue to keep this open while the team figures out issue #172 ( Web - Page Language Changes on Page Refresh but Text Stays in non-English Language ).

**Comment by jfc3-dol** [comment]
@pbhatt17 

Issue #172 ( Web - Page Language Changes on Page Refresh but Text Stays in non-English Language ) is now closed, so I'm closing this one too.
