### ISSUE TITLE
Android - Home Screen - TalkBack Reading Menu Content Even When Closed

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#17]
TalkBack is reading the content of the "Menu" when the “Menu” is closed. It should only read the content when it’s open and not when it’s closed.

**Comment by KyleLivingstonDOL** [comment]
Hi John,

We've updated this and will be demo'ed on the next 508 compliance check after Sprint 7.

Best,
Kyle

**Comment by jfc3-dol** [comment]
When does sprint 7 end and when I will see the application, give or take a day or two?

**Comment by KyleLivingstonDOL** [comment]
> When does sprint 7 end and when I will see the application, give or take a day or two?

UAT for Sprint 7 (which is ongoing right now) will start on June 10.

**Comment by jfc3-dol** [comment]
Closing the issue because TalkBack is no longer reading all the items in the Menu and is now reading the button name and the first item on the screen after it.
