### ISSUE TITLE
Topic Pages - Remove Extra Heading Level One (h1) Step Text

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#173]
@harpreetsdev @pbhatt17 @Abbychalil

I noticed there are two heading level one (h1) items on the Topic pages for the web version of the application. The first one used to be the Step number and text the Topic belonged too. It is now hidden using CSS of "display: none;". Please remove it if not using it because if CSS does not load, you will have two heading level one (h1) items on the page.

**NOTE** - I assume this applies to iOS and Android as well as the web version i spotted it on.

Please see the attached screenshot to so an example page.

![ilab - comply chain - topic pages - please remove additional heading level one (h1) that is visually hidden on screen](https://user-images.githubusercontent.com/10423487/107050902-cbb18c80-6799-11eb-8bb7-1857cd2f0897.png)

**Comment by jfc3-dol** [comment]
Of the pages, I checked there does not seem to be two heading level one (h1) items anymore. But on the following page ( https://dolcontentdev.opadev.dol.gov/ilab/complychain/steps/3/topic/3 ), at least the heading level skips from heading level one (h1) to heading level three (h3).

I will leave this one until I have more time to check some more pages.

**Comment by pbhatt17** [comment]
@jfc3-dol 
on that particular topic those heading were h3 so we developed as h3. On same page you can see there is h2 heading "The Role of Government Entities in Social Compliance Systems". Based on document and heading level requested to us we developed it. Please let us know if all those h3 need to update as h2 on this particular page.

**Comment by jfc3-dol** [comment]
@harpreetsdev @pbhatt17 @Abbychalil

You are skipping a heading level by going from a heading level one (h1) to a heading level three (h3), which are highlighted on the page and in the code. There could be other pages with a similar issue if it's using a template.

Do you want me to start a new issue for this problem or leave this issue open instead?

Please see the attached screenshot.

![ilab comply chain - page is skipping a heading level](https://user-images.githubusercontent.com/10423487/121066760-40242880-c798-11eb-903a-afaa0e9dbdfe.png)

**Comment by jfc3-dol** [comment]
@pbhatt17 

After randomly checking a bunch of Topic pages it seems the issue of skipping heading levels has been corrected.

So I'm going to close this issue.
