### ISSUE TITLE
iOS - VoiceOver is Clearing Content on Home Page

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#185]
While using VoiceOver on the home page, it is visually clearing the main content while it was reading the hidden Menu, which it should not be doing.

Please see the attached screenshots.

**Screenshot example one**

![ilab comply chain - voiceover clearing content on home page - part 2](https://user-images.githubusercontent.com/10423487/116571144-cebfa300-a8d8-11eb-90fd-0ab82ea68407.PNG)

**Screenshot example two**

![ilab comply chain - voiceover clearing content on home page - part 1](https://user-images.githubusercontent.com/10423487/116571167-d4b58400-a8d8-11eb-9a4f-932d1c770772.PNG)

**Comment by pbhatt17** [comment]
@jfc3-dol 
Please retest this issue. We are not able to reproduce it.

**Comment by jfc3-dol** [comment]
@pbhatt17 

While using VoiceOver to read the page in continuous reading mode (two-finger down swipe), the content no longer disappears as it did previously.

So I'm going to close the issue.
