### ISSUE TITLE
Android - Home Screen - Blue-Green Backgrounds Might be Difficult for Color Deficient (Colorblind)

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#20]
For those with color deficiencies (colorblind), it could be difficult for them to tell the green and blue imaged backgrounds apart. One of the main colorblindness’s is blue-green. Also, with having text over the colored image might not have enough color contrast to be read by most people.

Will look for a tool to check blue-green colorblindness issue. Can't seem to find the one that used to be online that you could upload an image, and it would show you the different looks by type.

Please see attached screen shot.

![android - home screen - color contrast and colro blindness](https://user-images.githubusercontent.com/10423487/57145228-c63b3d00-6d90-11e9-961e-55aa0f1901b9.png)

**Comment by KyleLivingstonDOL** [comment]
Hi John,

Thanks. We are addressing this issue.

-Kyle

**Comment by KyleLivingstonDOL** [comment]
Hi John,

We've updated this and will be demo'ed on the next 508 compliance check after Sprint 7.

Best,
Kyle

**Comment by jfc3-dol** [comment]
When does sprint 7 end and when I will see the application, give or take a day or two?

Can you upload a screenshot to this issue, so I can look at it sooner rather than later?

**Comment by KyleLivingstonDOL** [comment]
> When does sprint 7 end and when I will see the application, give or take a day or two?
> 
> Can you upload a screenshot to this issue, so I can look at it sooner rather than later?

Hi John,

I might be able to get a screenshot to you, but it might not translate well re: colors. The initial colors we saw on a screenshot =/= the colors in the app. However, if we can get you a screenshot earlier, we will do so. UAT for Sprint 7 (which is ongoing right now) will start on June 10.

**Comment by jfc3-dol** [comment]
Kyle,

I think one issue is for the difference between the blue and green Steps for those that are color deficient (colorblind) and the other is about the white text on colored backgrounds that have different color issues because some parts are lighter than others.

**Comment by jfc3-dol** [comment]
The Steps background images that are color tinged are now closer to each other so it's better from the color deficiency standpoint.

So we can close the issue.

Please see the attached screenshot.

![comply chain - main navigation with less blue-green issues for the background images](https://user-images.githubusercontent.com/10423487/59309521-c4a74380-8c71-11e9-8a74-3d72ab27c0e0.png)
