### ISSUE TITLE
Android - Home Screen - Poor Color Contrast of Main Content Section Buttons

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#21]
The color contrast of buttons in the main content section of the application with the white text ( #ffffff ) and the blue and green images is poor because of the lighter spots and make it difficult to read for those that have visual issues such as low vision or color deficient (colorblind).

The color contrast ratio for a different part of the colored images and the white text ranged on the low side from 2.97:1 to 3.82:1 when it needs to be 4.5:1 or higher to pass. Some of the words/letters have enough contrast, but lots of them don't.

Please see attached screenshot.

![android - home screen - color contrast and colro blindness](https://user-images.githubusercontent.com/10423487/57145707-cab42580-6d91-11e9-8046-8ff89eef23e6.png)

**Comment by KyleLivingstonDOL** [comment]
Hi John,

It looks like (though correct me if I am wrong), this is similar to #20. UAT for Sprint 7 (which is ongoing right now) will start on June 10. So we'll be able to get you a 100% working element to test at that point.

-Kyle

**Comment by jfc3-dol** [comment]
The color contrast has improved for the white text against the images with color tinge has poor color contrast but still is in the 3.25:1 to 3.98:1 range and needs to be 4.5:1 or higher to pass.

Please attached screenshot.

![comply chain - main navigation with less blue-green issues for the background images](https://user-images.githubusercontent.com/10423487/59309723-4f883e00-8c72-11e9-88e9-0854d3a4be6b.png)

**Comment by KyleLivingstonDOL** [comment]
ZTI, we can talk about this on Thursday.

**Comment by jfc3-dol** [comment]
Changing the color from green to red still is has color contrast issues because of the lighter image parts behind the white text make it difficult for people that are color deficient (colorblind) or have low vision able to read it. The best way to fix the issue would be to remove the images, so there is one set of color to get enough color contrast for the white text.

**Comment by KyleLivingstonDOL** [comment]
The images are important to ILAB as we've received positive reviews from other colleagues who have tested the application. We could try to make the images more transparent. ZTI, can we increase transparency?

**Comment by jfc3-dol** [comment]
Making the red and blue hue darker over the images should help, but I can't guarantee that will work without seeing them with the white text over them. Once the hue/images are made darker can I get a screenshot of all the items on the home page before the build is sent so I can check them and adjustments can be made if necessary?

**Comment by jfc3-dol** [comment]
The home screen color contrast is now improved with the darker and more saturated colors over the images with white text.

I'm closing the issue because the color contrast has been improved and we will re-open if we hear from people that it's difficult to read the white text.

Please see the attached screenshot.

![comply chain - English - home screen - color contrast is now improved with the darker and more saturated colors over the images with white text](https://user-images.githubusercontent.com/10423487/64365439-1d247d80-cfe2-11e9-8b7c-a1ab7aede463.jpg)
