### ISSUE TITLE
Android - Steps Screen - "Plus" and "Dash" Not Stating It's State

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#31]
At the end of the four light gray boxes/headings, TalkBack reads “Plus”. Doing this does not help the TalkBack user at all. I was expecting it to read “WHATEVER SECTION Button double tap to expand and see other content” or something like that. TalkBack need to notify the user there is more content hidden and what content it is? If an item is open, it should tell the user that the minus/dash can be double tapped to close it. The user needs to know the state of the item.

Please see attached screenshot.

![android - steps screen - plus and dash not stating their state](https://user-images.githubusercontent.com/10423487/57154954-238eb880-6da8-11e9-8d02-2fa4a8e7ae72.png)

**Comment by KyleLivingstonDOL** [comment]
It looks like this is complete. UAT beings June 10.

**Comment by jfc3-dol** [comment]
Closing issues because TalkBack is telling the user that the item is collapsed or expanded correctly.
