### ISSUE TITLE
Android - Steps Screen - TalkBack Reading Hidden Text

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#32]
TalkBack is reading the content that is hidden from the screen visually. It should only be read when it’s open.

Please see the attached screenshot that highlights where the hidden content is being read. If the open one were closed, it would read that one too. The four section are the following:

The four items I'm referring to are the ones listed below:

- Learning Objectives
- Key Terms
- Topics
- Further Resources

![android - steps screen - talkback reading hidden text for these items](https://user-images.githubusercontent.com/10423487/57155194-d19a6280-6da8-11e9-885c-7406477b64b2.png)

**Comment by KyleLivingstonDOL** [comment]
It looks like this is complete. UAT beings June 10.

**Comment by jfc3-dol** [comment]
Closing issue because TalkBack is not reading hidden text as expected.
