### ISSUE TITLE
Android - Steps Screen - TalkBack Starts at Sub-navigation and Skips Over "Bookmark" Button

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#35]
When choosing a “Topic” from the “Steps” screen, TalkBack starts reading at what I’m calling the sub-navigation of number. TalkBack skips over the “Bookmark” button and then goes the heading level one (h1).

**Comment by KyleLivingstonDOL** [comment]
It looks like this is complete. UAT beings June 10.

**Comment by jfc3-dol** [comment]
TalkBack is still reading the the "Bookmark" link after tapping on the "Next Topic" link/button at the bottom of the screen and switching the next topic.

**Comment by KyleLivingstonDOL** [comment]
ZTI, please address.

**Comment by jfc3-dol** [comment]
The problem looks to be fixed so going to close the issue.
