### ISSUE TITLE
Android - General - Display of Language Buttons issue between Table and Phone

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#4]
When using a tablet and having the “**Menu**” open the language buttons are way down the screen. 

For those with visual issues that need to zoom in to read items, they might miss them with being so far down.

Please see attached screenshots of the table and phone screens with the menu open.

**Tablet screen menu open.**

![android - home screen - why is there so much extra space between navigation and language on a tablet compared to a phone](https://user-images.githubusercontent.com/10423487/57088133-a09a2f00-6ccf-11e9-9357-7af621985efe.png)

**Phone screen menu open.**

![android - home screen - there is less space between navigation and language on a phone compared to a tablet](https://user-images.githubusercontent.com/10423487/57087861-020dce00-6ccf-11e9-8d0f-00fadce7e9a1.png)

**Comment by KyleLivingstonDOL** [comment]
Hi John,

Thanks for this. Can you please explain the 508 compliance issue with this, so we can better address it? With a tablet, there is no zoom function that I am aware of (but I will double-check with our developers). As such, there is no zooming, rather it would be scrolling to the bottom, as with any other Topic page to get to the "previous/next" topic buttons.

-Kyle

**Comment by jfc3-dol** [comment]
Assistive technology users that use the built-in zoom function for iOS or other software might not notice the button so far down the screen. Some users use software to always zoom in so they can have the content large enough to read and they could think that there is now more content on the page when using their tablet and then miss the language buttons which could be useful if French or Spanish is their first language and English is not.

**Comment by KyleLivingstonDOL** [comment]
Thanks John. It seems this also tagged functional issue, rather than a 508 issue. Our very first splash screen when installing the app allows a user to change the desired language. We also -- as you saw -- offer this via the menu button, so it is always available to users. As we are writing an app for all three major platforms, it would be very difficult and would detract from the app's continuity to change the arrangement and spacing in the menu.

I suggest we can close this issue out.

Thanks,
Kyle

**Comment by KyleLivingstonDOL** [comment]
Hi John,

Again, thanks for pointing this out. We understand the implications of using a screen magnifier can have when using a web/mobile application and have taken those into consideration. After discussing with our contractors, and seeing that this is a functional issue, **we would like to close this out**. We have ensured that there are several ways for a user to change languages. Further, as a screen magnifier can be used in any part of the application, users whom are utilizing screen magnifiers could also scroll right past content. As the language buttons are stickied at the bottom of the page to allow for the collapsible menu (STEPS), we cannot move them without redoing the entire menu layout.

Thanks so much!
Kyle

**Comment by jfc3-dol** [comment]
Kyle,

Thanks, for the update. I will close it when I get the next build and work my way through all the open issues.

**Comment by jfc3-dol** [comment]
It looks like now you first have the user set their language and then show them the two questions followed by the eight Steps.

Closing issue.
