### ISSUE TITLE
Android - TalkBack is Reading DOL Seal Incorrectly

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#41]
While using TalkBack to read the application I noticed that it's reading the DOL seal as "Brand strip logo" instead of "United States Department of Labor seal".

You will need to use the correct text updates for English, Spanish, and French, meaning they will need to be translated for French and Spanish.

**Comment by KyleLivingstonDOL** [comment]
ZTI: please program the seal to read as "U.S. Department of Labor"

**Comment by jfc3-dol** [comment]
Please spell out "U.S. Department of Labor seal" so screen reader users will know what it means such as "United States Department of Labor seal". Not everyone will understand what it means.

**Comment by KyleLivingstonDOL** [comment]
Thanks John. ZTI, please label it "United States Department of Labor seal"

**Comment by KyleLivingstonDOL** [comment]
I am working on the translations and we will have this done.

**Comment by jfc3-dol** [comment]
The DOL seal is now being read by TalkBack as "United States Department of Labor seal". So I'm going to close this issue
