### ISSUE TITLE
Android - TalkBack Not Pronouncing ILAB Correctly

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#42]
TalkBack is only reading ILAB as "ill ab". Think it would be best to spell it out and add ILAB at the end such as "Bureau of International Labor Affairs" or "Bureau of International Labor Affairs - ILAB".

**Comment by KyleLivingstonDOL** [comment]
ZTI: Please program ILAB to read as "Bureau of International Labor Affairs."

**Comment by KyleLivingstonDOL** [comment]
I am working on the translations and we will have this done.

**Comment by jfc3-dol** [comment]
The ILAB is now being read by TalkBack as "Bureau of International Labor Affairs ". So I'm going to close this issue
