### ISSUE TITLE
Android - After Activating Menu Main Step Expand Focus Moves to Top of Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#43]
When I open the "Steps to a social compliance system' menu item, it then moves TalkBack's focus to the top of the application, and I have to read back through everything against to get to the individual Steps. IT should leave the focus there or on the first Step.

**Comment by KyleLivingstonDOL** [comment]
ZTI, can we put code in to do this?

**Comment by jfc3-dol** [comment]
TalkBack focuses on the now open "Steps to a social compliance system" toggle so the next thing that is read is Step 1.

Because this is fixed I'm going to close this issue.
