### ISSUE TITLE
Android - Steps Screen Reading Items as Heading Level Three (h1)

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#46]
When TalkBack reads from the top of the page in the continuous reading mode it reads the four items with the plus sign as heading level three (h3) but now doesn't tell the user they can tap or double tap to open the item to see more information.

**Comment by LeHaine** [comment]
This is currently a heading wrapped around a button. If I remove the heading then it no longer reads the heading but just the button.
```
<h3>
    <button>Tittle</button>
</h3>
```

**Comment by jfc3-dol** [comment]
Okay, I guess if we can do both it's more important to tell the user it can be opened or closed along being able to double tap to open or whatever was there before.

Going to leave this open so I can retest once the change has been made.

**Comment by jfc3-dol** [comment]
TalkBack is telling the user if the four show and hide buttons are collapsed or expanded, what the section is, and that it's a button. TalkBack also announces the status of the item as it changes.

So I'm going to close the issue.
