### ISSUE TITLE
Web - The Comply Chain Application Shows a Blank Page in IE 11

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#48]
On my DEV machine (Windows 7), the testing tools I use for the DHS Trusted Tester process are on in IE. I get a blank white screen when I use the URL - https://dolcontentdev.opadev.dol.gov/ilab/complychain/build/, but the page renders in both Firefox and Chrome.

According to GSA's analytics tool ( https://analytics.usa.gov/labor/ ), DOL gets about 19% of its traffic from IE 11 and Edge, so it's not like it's a small number of people.

I will see what I can do using another browsers with some of the necessary tools to be able to test for accessibility issues.

**Comment by jfc3-dol** [comment]
@LeHaine,

The page now displays in IE 11.

I am wondering if it has been tested in Edge too before I close this issue?

**Comment by LeHaine** [comment]
Yep it was running fine in both IE11 and Edge.

**Comment by jfc3-dol** [comment]
Thanks, I will close the issue then, since I have not used my Windows 10 machine is a long time, and it will ask me or reboot my machine because of updates.
