### ISSUE TITLE
Adroid - General - Why is Numbered Circles (Sub-Navigation) on Non Steps or Topics Screens?

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#5]
Why is the numbered circles (sub-navigation) on non Steps or Topics screens there? I would expect them on the Steps and Topics screens so you can easily change Steps. They look like sub-navigation that don't work if they are supposed to .

The following are two of many screens that have them in it but are not a Step or Topic screen.

**The basic social compliance system screen.**

![android - basic social compliance system question screen - why is what looks like the Steps on this screen](https://user-images.githubusercontent.com/10423487/57093894-09d46f00-6cdd-11e9-9ff1-09bca2dd6377.png)

**Bookmarks screen**

![android - bookmarks screen - why is what looks like the Steps on this screen](https://user-images.githubusercontent.com/10423487/57093914-1d7fd580-6cdd-11e9-8048-088103e80370.png)

**Comment by KyleLivingstonDOL** [comment]
I think this issue is now resolved and will be demo'ed via the next 508 check after Sprint 7.

Best,
Kyle

**Comment by jfc3-dol** [comment]
The Steps at the top of the screen have been removed from the "why develop a social compliance system?" and "Basics of a social compliance System" screens, along with the "Bookmarks", etc screens, so going to close the issue
