### ISSUE TITLE
Web - Footer Not Center-aligned in IE 11

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#50]
For some reason, the footer navigation is right-aligned in IE 11 and center-aligned for both Firefox and Chrome. I didn't have Edge easily available so you might want to look at that too. Or maybe it's fine that the footer alignment is different between browsers.

**Firefox or Chrome footer is center-aligned**

![comply chain - english - firefox or chrome - footer center aligned](https://user-images.githubusercontent.com/10423487/60460914-0db83b00-9c13-11e9-92e5-6a5de56c978d.png)

**IE 11 footer is right-aligned**

![comply chain - english - ie 11 - footer rigth aligned](https://user-images.githubusercontent.com/10423487/60460915-0db83b00-9c13-11e9-8a9d-fd9acf84b15c.png)

**Comment by KyleLivingstonDOL** [comment]
Thanks John. ZTI, can this be fixed easily?
-Kyle

**Comment by jfc3-dol** [comment]
The Footer icons are now displaying properly in IE 11, so I'm going to close the issue.
