### ISSUE TITLE
Web - Search Page - In IE 11 the Magnifying Glass Alignment in Search Box is Wrong

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#51]
The magnifying glass icon is displaying under the search INPUT field when using IE 11. I didn't have Edge easily available so you might want to look at that too.

Search - https://dolcontentdev.opadev.dol.gov/ilab/complychain/build/search

**Magnifying glass icon alignment in search box**

![comply chain - poor magnifying glass alignment in search box](https://user-images.githubusercontent.com/10423487/60461648-2b869f80-9c15-11e9-8322-52cbaf464d85.png)

**Comment by KyleLivingstonDOL** [comment]
Thanks John. ZTI, can this be fixed easily? I understand that most builds are optimized for Chrome, but can this be fixed without affecting Chrome functionality?
-Kyle

**Comment by jfc3-dol** [comment]
There most likely people are going to use the application in IE, Edge, Chrome, Safari, and Opera on desktop and laptop computers. But they probably will look at them on tablets too using the mobile versions of those browsers.

GSA posts users statistics for the whole government along with each agency. They show a breakdown of the last 90 days by device type (desktop/laptop, mobile, and tablet) along with browser and operating system.

Here is a link to the Department of Labor's numbers - https://analytics.usa.gov/labor/

**Comment by jfc3-dol** [comment]
The Search icon in the is now displaying properly in IE 11, so I'm going to close the issue.
