### ISSUE TITLE
Web - Search Page - Not Able to Search with IE 11

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#52]
Not able to search using IE 11. Entered the term "test" and hit enter and nothing happened but search works as expected in Firefox and Chrome.

Search - https://dolcontentdev.opadev.dol.gov/ilab/complychain/build/search

**Comment by KyleLivingstonDOL** [comment]
Thanks. ZTI, can we fix this?
-Kyle

**Comment by trevitalgit** [comment]
![image](https://user-images.githubusercontent.com/53573580/63162317-3abc8380-bff0-11e9-9f98-c52146fa925b.png)

**Comment by jfc3-dol** [comment]
@trevitalgit,

Thanks, will give it a look when I have time next to review Comply Chain web version.

**Comment by jfc3-dol** [comment]
@harpreetsdev @Abychalil @pbhatt17 

Now able to search using IE 11, Edge, Chrome, and Firefox, so I'm going to close the issue.
