### ISSUE TITLE
Web - Bookmark List - "Undo" Button Not Displaying Porperly with IE 11

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#53]
When I use the bookmark button on a page in IE 11, the "Undo" button in the pop-up is not displaying properly — only seeing the first part of the button.

Bookmark List - https://dolcontentdev.opadev.dol.gov/ilab/complychain/build/bookmarks

Please see the attached screenshot.

**Bookmark "Undo" button not displaying properly in IE 11**

![comply chain - english - bookmark UNDO button not displaying properly IE 11](https://user-images.githubusercontent.com/10423487/60461876-da2ae000-9c15-11e9-8e4a-d9a7595e5345.png)

**Comment by KyleLivingstonDOL** [comment]
Hi ZTI, can we fix this?

**Comment by jfc3-dol** [comment]
The "Undo" pop-up and button for keeping a deleted bookmark is now displaying as expected in IE 11. so I'm going to close the issue.
