### ISSUE TITLE
Web - User Not Able to Open Step Sub-Menu in the Main Menu with Keyboard

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#54]
User is not able with a keyboard to open the "**Steps to a Social Compliance System**" section of the menu. 

The text "Steps to a Social Compliance System" in the menu looks to be and acts like a link but it not a link and won't open the list of Steps in the menu with a keyboard.

**Comment by KyleLivingstonDOL** [comment]
Thanks John. I am not as familiar with this functionality, but I am assuming you are referring to using the TAB key to tab over to different links to open them? If so, ZTI, can we fix this?
-Kyle

**Comment by jfc3-dol** [comment]
In the MENU, the eight Steps are hidden under the "Steps to a Social Compliance System" link where you see the right-pointing arrow in the circle.

A user can't open that section of the MENU to see the eight Steps with a keyboard. To get to the Steps, the user would have to then back tab to the "Homepage" link outside the MENU and then tab to the Step they want to look at in the main content section of the home page.

**Comment by Abychalil** [comment]
Fixed. User can now open the "Steps to a.." link under the Menu and access all the steps inside it with the tab key

**Comment by jfc3-dol** [comment]
@Abychalil,

Thanks for allowing the user to use a keyboard to open additional part of the menu. 

Will look at it when the next version/build is sent, and I  have time to test.

**Comment by jfc3-dol** [comment]
I'm able to open the Main Menu and then the sub-menu item after closing my browser because it was not opening the Main Menu after attempting to go to other places in the application. It seems like the code is causing some functions to work for a bit then not later.

I'd like to keep this open to check this more because I think it's part of a larger issue with keyboard focus.

**Comment by KyleLivingstonDOL** [comment]
@jfc3-dol Thanks for testing this. Is this a browser compatibility issue (is this reproducible in Chrome/IE/Firefox) or is this a code issue within Comply Chain?

**Comment by jfc3-dol** [comment]
@KyleLivingstonDOL,

Once I have the link after switching DEV laptops, I will give this issue a text in as many browsers as I can with my screen reader JAWS. I might not be able to text with Firefox but will see since I used to have issues on my old laptop.

**Comment by KyleLivingstonDOL** [comment]
Thanks John. Please let me know once you've switched so we can hopefully close this issue out.

**Comment by jfc3-dol** [comment]
@KyleLivingstonDOL,

Looking through old mail in the "Other" tab, I noticed this issue was there and still open.

I can use a keyboard to open and close the Menu button and the item to open the list of Steps within the Menu using IE 11, Edge, Chrome, and Firefox.

But none of them tell a screen reader user that these items can be Expanded or Collapsed along with not notifying them that it has happened.

**Comment by jfc3-dol** [comment]
@Abychalil 

While using my screen reader JAWS in IE and Chrome, it tells me that the sub-menu is a button. So when I use the "Enter" key or space bar, JAWS tells me which one I used. It does not tell the user that they either expanded/opened or collapsed/closed the sub-menu.

ARIA live region is what would be used to make these types of announcements to the user.

**Comment by jfc3-dol** [comment]
@harpreetsdev @Abychalil @pbhatt17

I am closing the issue because you can not open and close the Menu and sub-menu items with a keyboard in Ie11, Edge, Firefox, and Chrome.

Going to open another issue because neither the Menu or sub-menu items announce to the screen reader user that the item is now open or closed.
