### ISSUE TITLE
Web - User has to Back Tab to get to "About" Information

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#56]
User has to back tab to get to the items that pop-up from the "About" button/link once it is opened.

**Comment by KyleLivingstonDOL** [comment]
Thanks. ZTI, can we fix this?

**Comment by Abychalil** [comment]
tab order is fixed for the bottom navigation bar and the About drawer once its opened..

**Comment by jfc3-dol** [comment]
@Abychalil,

Thanks for correcting the tabbing and usability of the footer items along with the "About" pop-up links.

Will look at it when the next version/build is sent, and I  have time to test.

**Comment by jfc3-dol** [comment]
After rebooting my browsers (Chrome and IE 11) and JAWS by rebooting my laptop, I'm now able to get to the "About" button/link in the footer and navigate to the different items in the pop-up and open them with a keyboard.

So I'm going to close this issue.
