### ISSUE TITLE
Web - Extra Tab Stops in Footer and Home Page in IE 11

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#57]
In IE 11 the user has to tab twice in the footer to get from one item to the next. Guessing it might have to do with the link text and the SVG image as two parts of the same link for each one.

**Comment by KyleLivingstonDOL** [comment]
I think it might be. I'm not sure if we can automatically have the tab skip the image. @jfc3-dol , if we do have the tab skip the image, would this be a 508 issue? If so, I think we need to keep the current functionality.

**Comment by trevitalgit** [comment]
Kyle, should I just keep the current functionality as is?

**Comment by jfc3-dol** [comment]
@KyleLivingstonDOL and @trevitalgit,

When I have a moment to look at this again, I will look at the code and see if there is a way to fix it and also check with friends to see if it might browser-specific issue.

**Comment by jfc3-dol** [comment]
There are still two tab stops in the footer for each item along with those in the Main page content section that seem to have SVG /icons.

**Comment by Abychalil** [comment]
Development in progress

**Comment by jfc3-dol** [comment]
Found the fix for the IE 11, and older browsers need to double tag when SVG icons are used in links.

IE 11 and older IE browsers have an issue were when tabbing to items that have SVG images such as those in the footer icon links or the ones on the home page will make the keyboard-only user have to tab a second time to get to the next item.

I found out this was a known issue a while ago and not had time to find out if there was a fix. So late on a Sunday night (11:00 PM) a month ago while reading the book "Form Design  Patterns", the author Adam Sliver mentioned to correct that issue you add **focusable="false"** to the SVG image and the issue goes away in IE 11 and older IE browsers.

So I created a test page with the current set of social media links from DOL.gov and then a second set with the extra code ( **focusable="false"** ), which then fixed the issue when I tested it.

I then had the OPA Content team post my test page on the DEV server so I could have others test it in IE 11 and a few other browsers to make sure it did not cause issues for them. We all found that it fixed the problem.

 So please give it a test in IE 11 by tabbing through the first set of social media links to see there is an extra tab needed to get to the next link. Then in the fixed section of the page, you only need to tab once to get to the next links.

So here is the test social media icon page link.

https://dolcontentdev.opadev.dol.gov/test/steo/social-media-icons.htm

If you have any questions, please get in touch.

**Comment by jfc3-dol** [comment]
@Abychalil,

There is no longer and extra tab stop in the footer link/SVG icons in IE because the code focusable="false" has been added. Added that code did not change the way I was able to tab through the footer in Edge, Chrome, and Firefox. 

So I'm going to close this issue.
