### ISSUE TITLE
Web - Menu Stays Open After Tabbing through Items

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#58]
If the user opens the Menu and tab through the items, the menu stays open once I'm through the items. I would expect it to close so I can see the content it might be blocking.

**Comment by KyleLivingstonDOL** [comment]
John, when the user reaches the end of the list in the menu, does the tab functionality return to the top of the menu? If so, then I would like to keep it that way so the user can go through the menu again without having to tab through the entire page. If the tab functionality moves to the next item on the page outside of the menu, then ZTI, can we please have the tab functionality return to the top of the menu so the user can elect to either close the menu or tab through again without going through the entire page?

**Comment by jfc3-dol** [comment]
Yes, if a user opens the MENU button with a keyboard and then tabs through all the items, it goes to the next item on the page.

As you stated, I would like it to either go back to the top so a person can close it or go through the items again or close and then head to the next item they can tab to on the page.

For example on the home page the user tabs through the menu items once they opened it and then for to the "Why Develop a Social Compliance System?" link at the top of the main content section of the page.

**Comment by trevitalgit** [comment]
When the tab reaches to bottom navigation icons, do I need to hide the menu?

**Comment by jfc3-dol** [comment]
Not able to open the Menu with a keyboard. It seems the visual focus, when available, does not match the keyboard focus, which does not move.

**Comment by jfc3-dol** [comment]
Once I rebooted laptop, browser, and screen reader, I could get the Main Menu open, and when I tabbed past the last item in the menu, it stayed open.

**Comment by Abychalil** [comment]
fixing in progress

**Comment by Abychalil** [comment]
This issue is fixed. Now, the menu will get closed after the user tabs through all the menu items. Similar issue with the About button also fixed.

**Comment by Abychalil** [comment]
Addressed this issue. Please retest and verify whether it meets the required 508 standards. 
@jfc3-dol

**Comment by jfc3-dol** [comment]
@Abychalil,
After opening the Menu, I can tab past the last item, and the Menu still stays open. If the person is looking at it on a narrower screen, the Menu can block the page content. The attached screenshot shows that the Menu blocks the text for Step 4 in this example.

![comply chain - web - menu stays open after tabbing past the last item in it](https://user-images.githubusercontent.com/10423487/75275435-87b8b800-57d2-11ea-8678-bc2ee44abd6d.png)

**Comment by jfc3-dol** [comment]
It's hard to see but while on the Steps 1 Topic 1 screen I opened the Menu and tab out of it and it did not close so part of the content is cut off. You can see where I have tabbed to by the highlighted red box. I would expect the Menu to close once I'm out of it. The same issues apply to the home page and others too.

Please see the attached screenshot.

![ilab - comply chain - Menu does not close when tabbing out of it which blocks content](https://user-images.githubusercontent.com/10423487/85759949-5fd55480-b6df-11ea-94a6-cf4e2c7022d6.png)

**Comment by KyleLivingstonDOL** [comment]
Adding Sandi, as I am not sure if she is on this distribution list.

-Kyle

**Comment by Abychalil** [comment]
Menu was closing when the focus moves out of the Menu. It was working fine in my system when I tested. Let me work with our developers and see why it happens.

**Comment by jfc3-dol** [comment]
@Abychalil 
Maybe it's the browser you're using to test. For IE 11, it works but not the others on my PC Windows 10 machine.

**Comment by jfc3-dol** [comment]
@Abychalil 

If the Main Menu is open and I tab past the last item in the list, it closes as expected in IE, Edge, Chrome, and Firefox on my DEV Windows 10 machine.

So I'm going to close this issue.
