### ISSUE TITLE
Web - Develop Social Compliance System - User Not able to Open Show/Hide Content with Keyboard

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#59]
When tabbing the user shouldn't skip over or not able to tab to the handful of items with the plus sign (+) that opens up more content with a keyboard because the tab order skips from the link starting with "Executive Order 13126, Prohibition..." and then goes to the link starting with " Organization for Economic Cooperation...".

The problem applies to other pages that have the show/hide content. 

Please make sure to correct those pages too.

Develop Social Compliance System - https://dolcontentdev.opadev.dol.gov/ilab/complychain/build/why-develop

**Comment by KyleLivingstonDOL** [comment]
ZTI, please address for all collapsible boxes.

**Comment by Abychalil** [comment]
Fixed in another issue.

**Comment by jfc3-dol** [comment]
@Abychalil,

Thanks for correcting the issue. Will look at it when the next version/build is sent, and I  have time to test.

**Comment by jfc3-dol** [comment]
Not able to open the show/hide content with a keyboard because the keyboard focus does not go to them. Plus, I can't see the visual focus even though the page moves like it's being tabbed to items farther down the screen.

**Comment by KyleLivingstonDOL** [comment]
ZTI can you please take another look at this? Thanks.

**Comment by Abychalil** [comment]
Sure, Noted Kyle. Created new ticket for this issue in our Jira. We will be looking into it sooner. Thanks. 
@KyleLivingstonDOL

**Comment by jfc3-dol** [comment]
Closing the issue because I can open and close the items in IE 11, Chrome, and Firefox even though it's hard to tell where you are with IE 11.
