### ISSUE TITLE
Android -  Non home Page - Menu Stays Open after Tapping Home Page Button

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#6]
Why when the “Menu“ is open and you then tap on the “Homepage” back button does the menu still stay open, but the screen changes below to the home page screen? I would expect that the menu would close when I went to the home page screen.

Please see screenshots.

**Non home page screen with menu open.**

![android - menu open on non home screen showing home page back button](https://user-images.githubusercontent.com/10423487/57097847-c2eb7700-6ce6-11e9-8184-f45af9506e15.png)

**Home page screen with menu open.**

![android - home screen - clicked home page button on previous screen and application went to home page but kept menu open](https://user-images.githubusercontent.com/10423487/57097877-d26ac000-6ce6-11e9-972e-731f90ba2a0d.png)

**Comment by KyleLivingstonDOL** [comment]
Hi John,

I think we've rectified this issue. When we resubmit for 508 compliance check, we can see if it is still doing this.

Thanks,
Kyle

**Comment by jfc3-dol** [comment]
Thanks, looking forward to checking that this issue has been fixed.

**Comment by jfc3-dol** [comment]
On some screens, when the menu is open, and I tap the "Homepage" button, it closes the menu and takes the person to the home page. While other times when tapping on the "Homepage" button, it closes the menu but won't go to the home page until you tap it again.

Going to need to figure out what the issue is before giving suggestions on what the issues are or how to fix.

**Comment by KyleLivingstonDOL** [comment]
Hi John, I cannot replicate this. I've checked on several pages and tapping on the home page with the menu open closes the menu and goes directly home. Can you please test it on a page and let me know which on you've tested it on? That way I can replicate and flag for our contractors.

Thanks,
Kyle

**Comment by jfc3-dol** [comment]
Let me try it again with and without TalkBack when I get a chance because it wasn't doing it all the time but once in a while when I used TalkBack at least.

If it happens, I will keep track of the screens it happens on which I didn't previously. Maybe some code that needs to be there is not for some reason, but I would assume it's in all the pages.

**Comment by KyleLivingstonDOL** [comment]
Thanks John! Appreciate it. It could be on just one or two pages, so we can address those pages directly.

Thanks,
Kyle

**Comment by jfc3-dol** [comment]
It will take a bit since there are eight Step pages and all the related Topic pages that go with each group, but I think it was more one of the Step pages. Will check later this afternoon.

**Comment by KyleLivingstonDOL** [comment]
Thanks John. Any update on this?

**Comment by jfc3-dol** [comment]
Haven't had an hour or more to be able to look at each individual Topic page under each Step. Because when testing the Menu open and clicking on the "Homepage" link/button I have to start over each time to get to the Step and then the next Topic within that Step. All while using TalkBack will take a few hours, and I figured my time was better spent attempting to text the web and iOS version of the application along with the Spanish and French screens/pages.

**Comment by jfc3-dol** [comment]
After doing some random testing of opening the Menu and then going back to the "Home Page" link/button, the Menu closes after tapping on the "Home Page" link/button.

So I'm going to close this issue.
