### ISSUE TITLE
Web - Tab Order Not Logical When Using "About" Button

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#60]
User has to back tab to get to the items that pop-up from the "About" button/link after they are opened. To get to the three menu items for that pop-up when they activate the "About" button/link they have to back tab through the other items in the footer. The three items are tabbed from the bottom to the top. I would expect the focus to go to the first item in the list (top) and then tab to the next two items.

**Comment by KyleLivingstonDOL** [comment]
ZTI, can we fix this?

**Comment by jfc3-dol** [comment]
Not able to open the "About" pop-up with a keyboard using IE 11 or Chrome.

**Comment by jfc3-dol** [comment]
After rebooting my browsers (Chrome and IE 11) and JAWS by rebooting my laptop, I'm now able to get to the "About" button/link in the footer and navigate to the different items in the pop-up and open them with a keyboard.

So I'm going to close this issue.
