### ISSUE TITLE
Web - Step 5 - User Not able to Open Show/Hide Content with Keyboard

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#61]
Not able to open any of the four closed sections with the plus sign (+) with a keyboard because the tab order skips from the bookmark icon/button and then goes to the "Previous Step" link.

Step 5 - https://dolcontentdev.opadev.dol.gov/ilab/complychain/build/steps/5

**Comment by KyleLivingstonDOL** [comment]
ZTI, please address.

**Comment by Abychalil** [comment]
tab functionality set to all the links under step 5 and now user can navigate using the keyboard through the page
Fixed

**Comment by jfc3-dol** [comment]
@Abychalil,

Thanks for correcting the tabbing issues with the links under Step 5. 

Does this fix apply to all the other Topic screen?

Will look at it when the next version/build is sent, and I  have time to test.

**Comment by jfc3-dol** [comment]
Keyboard, only users, can now open and close the show and hide content items, but they have no visual indication of where they are on in the screen.

So I'm going to close this issue and open another one for the visual focus issue.
