### ISSUE TITLE
Web - User Not Able to Delete Bookmark with Keyboard

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#62]
User is not able to tab to the bookmark icons with a keyboard to be able to delete an item from the list. Once a user does delete a bookmarked item, the keyboard focus does not go to the "Undo" button so by the time they figure which way to tab the pop-up window is gone.

Bookmark List - https://dolcontentdev.opadev.dol.gov/ilab/complychain/build/bookmarks

**Comment by KyleLivingstonDOL** [comment]
ZTI, can we have the tab functionality jump directly to the undo button if a user elects to remove a bookmark? If so, let's build that in.

**Comment by Abychalil** [comment]
Tab functionality added to the Undo Button. Also focus set to the undo button when the user unbookmark any page link from the listed items

**Comment by jfc3-dol** [comment]
@Abychalil,

Thanks for correcting the "Undo" button issues. Will look at it when the next version/build is sent, and I  have time to test.

**Comment by jfc3-dol** [comment]
I can now delete the bookmark with the keyboard, but a keyboard-only user can not tell where they are on the screen. There is no visual indication of where they are on the screen.

Will close this issue because you can now delete a bookmarked item, but open a new issue that the user can't tell on either IE 11 or Chrome where they are on the screen since there is no visible focus.
