### ISSUE TITLE
Web - No Langauge Set for "Español" and "Français" in Menu

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#63]
The word for Spanish "Español" ( lang="es" ) and the word for French "Français" ( lang="fr" ) should each have the proper language set for them in the menu and on the home page the first time you are there, so they are pronounced properly for the screen reader user.

Please add a SPAN around each of the words using the code for the languages listed after them above.

The page language is set to English ( lang="en" ).

**Comment by KyleLivingstonDOL** [comment]
ZTI, can we do this?
@jfc3-dol , when you say "the first time" what exactly do you mean? I'm not following, but perhaps ZTI understands.

**Comment by jfc3-dol** [comment]
When the user first enters the application, it lists the three languages on the screen until you choose one. So those have to have the proper language set. 

Please see iPad screenshot.

![comply chain - ios - english - spanish and french txt on first home screen](https://user-images.githubusercontent.com/10423487/61413526-baecad80-a8b9-11e9-839e-859a648f682c.png)

**Comment by Abychalil** [comment]
Span added for each language
Fixed

**Comment by jfc3-dol** [comment]
@Abychalil,

Thanks for correcting the language issues for Spanish and French on the screen. Will look at it when the next version/build is sent, and I  have time to test.

**Comment by jfc3-dol** [comment]
Thanks for adding the different languages for the word Spanish "Español" ( lang="es" ) and the word French "Français" ( lang="fr" ) to the Main Menu. 

I'm not sure how I'm supposed to test these buttons that show on the screenshot above for the web since it only seems to only show for iOS and Android applications.

I will close this issue, and if people have and issue with the splash screen on the web, we can fix it later, since I don't expect to see it.
