### ISSUE TITLE
Android - General - Footer Links/Button Touch Size is Different

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#8]
The touch area for the “Share” and “About” links/buttons is only each of those words and not larger like the “Bookmarks” and “Search” button which highlights a much larger touch area.

Please notice the light blue border/focus ring from TalkBack the shows the size. Will only show two screenshots because the other items are similar.

**Example of “Bookmarks” and “Search” button touch size.**

![android - footer button touch size for booksmarks and search](https://user-images.githubusercontent.com/10423487/57104253-db16c280-6cf5-11e9-9b7f-877f6cb2c868.png)

**Example of “Share” and “About” button touch size.**

![android - footer button touch size for share and about](https://user-images.githubusercontent.com/10423487/57104239-d520e180-6cf5-11e9-8eed-563f12e11933.png)

**Comment by KyleLivingstonDOL** [comment]
It looks like this is done. UAT for Sprint 7 (which is ongoing right now) will start on June 10.

**Comment by jfc3-dol** [comment]
The "Share" and "About" touch areas highlighted by TalkBack are as large as the other two 

Closing issue.

Please see screenshot.

![comply chain - android - share and about button touch size is same as others](https://user-images.githubusercontent.com/10423487/59362036-ce2bbc80-8d00-11e9-816d-daef48ea9693.png)
