### ISSUE TITLE
Web - Bookmark List - User Not Focused on "Undo" Button after Deleting Record

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Comply-Chain#80]
User is not focused on the "Undo" button once they attempt to delete a bookmark using the bookmark icon.

Bookmark List - https://dolcontentdev.opadev.dol.gov/ilab/complychain/build/bookmarks

**Comment by KyleLivingstonDOL** [comment]
ZTI, is there a way to program the focus button to jump automatically to the undo button when a user removes a bookmark?

**Comment by jfc3-dol** [comment]
Or at least the pop-up window so the person can then read the text and use the "Undo" button if necessary.

**Comment by Abychalil** [comment]
Focus set for undo button 
fixed

**Comment by jfc3-dol** [comment]
@Abychalil,

Thanks for correcting the focus issues with the "Undo" button. Will look at it when the next version/build is sent, and I  have time to test.

**Comment by jfc3-dol** [comment]
The application now focuses on the "Undo" button after removing a bookmark, but JAWS/screen reader users are not notified of that so they and Undo their delete. Plus, JAWS continues to read content and then reads the "Undo" pop-up and button seconds after the "Undo" button and pop-up are gone.

**Comment by KyleLivingstonDOL** [comment]
Thanks John. ZTI, can we fix? Can we remove the focus ring from the "undo" button if a user undoes their bookmark delete?

**Comment by Abychalil** [comment]
Noted. Created jira tickets for this issue. We will be addressing this issue soon. Thanks! 
@KyleLivingstonDOL

**Comment by transreductionist** [comment]
There is currently a 5 second timeout on the `Undo` button. This means that, if the bookmark title takes more than 5 seconds to read the undo button will disappear before the "Undo" is read. Setting this to a higher timeout is probably not the way to solve the issue.

Here is a possible solution. We can remove the timeout and require the user to take an action:
- Tab away and remove the bookmark, and then let the `Undo` button disappear.
- Use `control-option-space` in VoiceOver to select the Undo button and return the bookmark to the list.

The other concern is that when the bookmarks are rendered after an undo they are being read incorrectly by VoiceOver. If I had bookmarks 1, 2, 3, and 4 on the page, then they read:
- step 1: reads - step 1
- step 2: reads - step 2
- step 3: reads - step 3

Now if I remove and undo step 1:
- step 2: reads - step 1, step 2
- step 3: reads - step 2, step 3
- step 1: reads - step 1

**Comment by jfc3-dol** [comment]
@transreductionist,

Having a longer time for the user to take action would be great. It's not a timeout message, but it's similar. The requirement for a timeout message is to have at least 20 sections to ask for more time. So giving the user at least 20 sections would allow assistive technologies like a screen reader to read the full message and the option to "Undo", too. But as you stated, some might be longer, and even 20 seconds might not be enough.

Most phone or tablet screen reader users do not use a keyboard, so not sure the "Control-Option-Space" option would be useful. Plus, it might be another set of keys for different screen readers besides VoiceOver.

Thinking about it for a bit if you get rid of the timeout option makes all users have to deal with the "Undo" option before doing anything else. If the person is a keyboard-only user, they would have to decide, or even a mouse user would have to close the pop-up before they could move on.

I'm confused about your Step's explanation. I think you meant if you remove Step 4?

I don't think it matters which order the Steps are once one is removed as long as it reads all of the ones listed on the screen, which I would expect to start at the top and work my way to the bottom or at least the ones after the one I removed.

Hopefully, the above was helpful. 

Maybe we could set up a meeting for a phone call if needed if that would help.

**Comment by transreductionist** [comment]
@jfc3-dol 

Thanks for the detailed response.

A telephone call would help ensure the changes meet expectations. Call anytime today at 703-200-8470, or let me know a number and time and I will give you a call.

I will program 20 seconds for the time out, or longer so that all VoiceOver content is read.

Sorry for the confusion on how VoiceOver reads the bookmarks. Here it is with a better explanation:
If I had bookmarks step 1, step 2, step 3, and step 4 on the page they are read as expected:

- step 1: VoiceOver reads "step 1"
- step 2: After tabbing to next bookmark in list VoiceOver reads "step 2"
- step 3: After tabbing to next bookmark in list VoiceOver reads "step 3"
- step 4: After tabbing to next bookmark in list VoiceOver reads "step 4"

I remove step 1 they are read in a confusing way because of a defect:

- step 2: VoiceOver reads "step 1, step 2"
- step 3: After tabbing to next bookmark in list VoiceOver reads "step 2, step 3"
- step 4: After tabbing to next bookmark in list VoiceOver reads "step 3, step 4"

**Comment by Abychalil** [comment]
Addressed this issue. Please retest and verify whether it meets the required 508 standards.
@jfc3-dol

**Comment by jfc3-dol** [comment]
@Abychalil,
When using the keyboard in Firefox, the focus goes to the "Undo" button as expected and allows the user to "Undo" the removal of the bookmark. But when I attempt the same thing in IE on the Bookmark page, it shows up as a blank screen instead of a list of bookmarks. I even tested it on someone else's computer and got the same results of no Bookmarks page.

**Comment by jfc3-dol** [comment]
@Abychalil 
When attempting to test in IE11, the "Bookmark" page comes shows up as a blank white screen with nothing else on it.

**Comment by jfc3-dol** [comment]
@Abychalil @KyleLivingstonDOL 
When using the keyboard in Firefox and Chrome, the focus goes to the "Undo" button as expected and allows the user to "Undo" the removal of the bookmark. If I decide to use the "Undo" button for these two browsers, the focus goes to the "Bookmarks" link in the footer. I would expect the focus to go back to the item I was attempting to delete.

When I attempt the same thing in IE on the "Bookmark" page, it shows up as a blank screen instead of a list of bookmarks. I even tested it on someone else's computer and got the same results of no Bookmarks page.

**Comment by Abychalil** [comment]
Yes, We are working on the above 2 issues mentioned.
@jfc3-dol

**Comment by jfc3-dol** [comment]
@Abychalil 

Okay, I will look at this issue and #108 related to bookmarks when you have had time to fix them.

**Comment by jfc3-dol** [comment]
@harpreetsdev @Abychalil @pbhatt17

When using the keyboard in Firefox, Chrome, IE 11, and Edge, the focus goes to the "Undo" button as expected and allows the user to "Undo" the removal of the bookmark. If I decide to use the "Undo" button for Firefox, IE 11, and Edge, the focus goes to the first bookmark. For Chrome, the focus goes to the "Bookmarks" link in the footer.

**Comment by harpreetsdev** [comment]
@jfc3-dol 

This might be a cache issue as well. Since chrome is our primary development browser, all issues get fixed in that first and then get tested on others. Please clear the cache and retest this one.

Let me know if you are still facing the same issue.

@pbhatt17 @Abychalil

**Comment by jfc3-dol** [comment]
@transreductionist @pbhatt17 @Abychalil

Closing issue because the cache issue looks to be gone for all browsers.
